services:
  - type: web
    name: audiostream
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0